
# Log4j 2 properties configuration
status = error
name = PropertiesConfig

# Console appender
appender.console.type = Console
appender.console.name = CONSOLE
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{dd MMM yyyy HH:mm:ss:SSS} %-5p %C{1} %X{reqId} %m%n

# Root logger
rootLogger.level = info
rootLogger.appenderRefs = console
rootLogger.appenderRef.console.ref = CONSOLE
