      queryParameters:
        persist_method:
          description: |
            Either save to temp dir or save to temp dir and notify via bus
          enum: [SAVE, SAVE_AND_NOTIFY]
          default: SAVE
          required: false
        bus_address:
          description: |
            The event bus address to publish the uploads to
          type: string
          required: false
          default: "admin.uploaded.files"
        file_name:
          description: |
            name of the file - a timestamp in milliseconds prefixes each saved file - if not passed will |
            be pulled from the header, Content-Disposition attachment; filename="fname.ext" - any path must be ignored
          type: string
          required: false
