      description: Collection of <<resourcePathName|!singularize>> items.
      is: [secured, language]

      get:
        description: Retrieve a list of <<resourcePathName|!singularize>> items.     
        responses:
          200:
            description: "Returns a list of <<resourcePathName|!singularize>> items"
            body:
              application/json:
                schema: <<schema>>
                example: <<exampleCollection>>
          400:
            description: "Bad request, e.g malformed request body or query parameter. Details of the error (e.g name of the parameter or line/character number with malformed data) provided in the response."
            body:
              text/plain:
                example: "unable to list <<resourcePathName>> -- malformed parameter 'query', syntax error at column 6"
          500:
            description: "Internal server error, e.g due to misconfiguration"
            body:
              text/plain:
                example: "internal server error, contact administrator"