
    description: Entity representing a <<resourcePathName|!singularize>>
    is: [secured, language]

    get:
      description: |
        Retrieve <<resourcePathName|!singularize>> item with given {<<resourcePathName|!singularize>>Id}
      responses:
        200:
          description: "Returns item with a given ID"
          body:
            application/json:
              example: <<exampleItem>>
              schema: <<schema>>
        404:
          description: "Item with a given ID not found"
          body:
            text/plain:
              example: |
                "<<resourcePathName|!singularize>> not found"
        500:
          description: "Internal server error, e.g. due to misconfiguration"
          body:
            text/plain:
              example: "internal server error, contact administrator"
    delete:
      description: |
        Delete <<resourcePathName|!singularize>> item with given {<<resourcePathName|!singularize>>Id}
      responses:
        204:
         description: "Item deleted successfully"
        404:
          description: "Item with a given ID not found"
          body:
            text/plain:
              example: |
                "<<resourcePathName|!singularize>> not found"
        400:
          description: "Bad request, e.g malformed request body or query parameter. Details of the error (e.g name of the parameter or line/character number with malformed data) provided in the response."
          body:
            text/plain:
              example: |
                "unable to delete <<resourcePathName|!singularize>> -- constraint violation"
        500:
          description: "Internal server error, e.g. due to misconfiguration"
          body:
            text/plain:
              example: "Internal server error, contact administrator"
 
    put:
      description: |
        Update <<resourcePathName|!singularize>> item with given {<<resourcePathName|!singularize>>Id}
      body:
          application/json:
            schema: <<schema>>
            example: <<exampleItem>>
      responses:
        204:
          description: "Item successfully updated"
        404:
          description: "Item with a given ID not found"
          body:
            text/plainn:
              example: |
                "<<resourcePathName|!singularize>> not found"
        400:
          description: "Bad request, e.g malformed request body or query parameter. Details of the error (e.g name of the parameter or line/character number with malformed data) provided in the response."
          body:
            text/plain:
              example: |
                "unable to update <<resourcePathName|!singularize>> -- malformed JSON at 13:4"
        500:
          description: "Internal server error, e.g. due to misconfiguration"
          body:
            text/plain:
              example: "internal server error, contact administrator"
 