DROP TABLE IF EXISTS users, groups cascade;
CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA public;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;
CREATE TABLE users (id UUID PRIMARY KEY DEFAULT uuid_generate_v1mc(), user_data JSONB NOT NULL, groupId UUID);
CREATE TABLE groups (id UUID PRIMARY KEY, jsonb JSONB NOT NULL);
