#%RAML 1.0

title: Jobs API
baseUri: http://localhost:8081/v1
version: v1

types:
  jobs: !include jobs.schema

/jobs:
  displayName: Jobs
  description: Jobs services
  post:
    body:
      application/json:
        schema: jobs
