
      headers:
        Authorization:
          description: |
            Used to send a valid JWT token.
          example: |
            Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ
          required: true
      responses:
        401:
          description: |
            No valid token found
          body:
            text/plain:
              example: "Unauthorized" 
        403:
          description: |
              Access denied not valid privilage in resurces
          body:
            text/plain:
              example: "Unauthorized"
