      queryParameters:
        view:
          description: |
            displays a [brief] or [full] view of the returned entities - for example: show <<view>> view of the entities
          type: string
          required: false
          default: brief