      queryParameters:
        lang:
          description: |
            Requested language. Optional. [lang=en]
          type: string
          required: false
          default: en
          pattern: "[a-zA-Z]{2}"