      queryParameters:
        reason:
          description: |
            Reason code
          type: string
          required: true
        comment:
          description: |
            Short comment
          type: string
          required: false
        notify:
          description: |
            Notify involved parties
          type: string
          required: false