      queryParameters:
        period:
          description: |
            The number of days/weeks/months to retrieve availability information for. Mandatory.
          type: string
          required: false
        period_type:
          description: |
            The type of period of interest. Optional. Possible values: days, weeks, months. Default: days.
          type: string
          required: false
          default: days