      queryParameters:
        level:
          description: |
            The log level to set the module's log to
          enum: [ERROR, SEVERE, WARN, WARNING, INFO, FINE, FINER, FINEST, DEBUG]
          default: INFO
          required: true
        java_package:
          description: |
            The package / class to set the logging level to, defaults to all packages
          type: string
          required: false
          default: "*"
