#%RAML 1.0
title: API with Types
types:
  User: !include user.schema

/users/{id}:
  post:
    description: Post user in XML format
    body:
      application/xml:
        type: string
    responses:
      201:
        description: OK
        body:
          application/xml:
            type: string
            example: "<x>y</x>"
      400:
        description: User Error
        body:
          text/plain:
            example: user error
  get:
    queryParameters:
      lang:
        description: Requested language
        type: string
        default: en
        pattern: "[a-zA-Z]{2}"
    responses:
      200:
        body:
          application/json:
            type: User
      400:
        description: Bad Request
        body:
          text/plain:
      404:
        description: Not Found
        body:
          text/plain:
