#%RAML 1.0
title: API with Types
types:
  User: !include user.schema

/users/{id}:
  get:
    queryParameters:
      lang:
        description: Requested language
        type: string
        default: en
        pattern: "[a-zA-Z]{2}"
    responses:
      200:
        body:
          application/json:
            type: User
      400:
        description: Bad Request
      404:
        description: Not Found
