      queryParameters:
        history:
          description: Whether to save returned values into a least recently inserted cache. |
            Every call to the API after calling with history=true will return results from up |
            to the previous 100 calls to this API
          type: boolean
          default: false
          required: false
