#%RAML 1.0

title: Msg API
baseUri: http://localhost:8081/v1
version: v1

types:
  msgs:   !include x/y/msgs.schema

/msgs:
    displayName: Msgs
    description: Msgs services
    post:
      body:
        application/json:
          schema: msgs
